name: Build Proton-base Wine (ARM64EC, WoW64) — cached

on:
  workflow_dispatch:
    inputs:
      wine_ref:
        description: 'ValveSoftware/wine ref (ex: proton_10.0)'
        required: true
        default: 'proton_10.0'

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PREFIX: ${{ github.workspace }}/_inst
      STAGE:  ${{ github.workspace }}/_stage
      TOOLCHAIN_ROOT: ${{ github.workspace }}/.toolchains
      LLVM_TC_DIR: ${{ github.workspace }}/.toolchains/llvm-mingw-arm64ec
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 4G
      CCACHE_COMPRESS: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 0) 캐시 디렉토리 준비
      - name: Prepare dirs
        run: |
          mkdir -p "$TOOLCHAIN_ROOT" "$CCACHE_DIR"

      # 1) 최신 FEX ARM64EC 툴체인 메타만 조회(캐시 키에 쓸 태그 추출)
      - name: Query FEX ARM64EC toolchain meta
        id: tcmeta
        shell: bash
        run: |
          set -e
          json=$(curl -fsSL https://api.github.com/repos/FEX-Emu/FEX/releases/latest)
          tag=$(jq -r '.tag_name' <<<"$json")
          url=$(jq -r '.assets[] | select(.name | test("arm64ec.*(ubuntu|linux).*x86_64.*\\.(tar\\.(xz|zst))$")) | .browser_download_url' <<<"$json" | head -n1)
          [[ -n "$tag" && -n "$url" ]] || { echo "FEX ARM64EC toolchain asset not found"; exit 1; }
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "url=$url" >> "$GITHUB_OUTPUT"

      # 2) 툴체인(압축본+해제본) 캐시
      - name: Cache toolchain (extracted)
        id: cache_tc
        uses: actions/cache@v4
        with:
          path: ${{ env.LLVM_TC_DIR }}
          key: llvm-mingw-arm64ec-${{ runner.os }}-${{ steps.tcmeta.outputs.tag }}

      - name: Download & extract toolchain if cache missed
        if: steps.cache_tc.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -e
          mkdir -p "$LLVM_TC_DIR"
          cd "$TOOLCHAIN_ROOT"
          file=$(basename "${{ steps.tcmeta.outputs.url }}")
          # 원본 압축본도 보조 캐시
          echo "::group::Fetch toolchain archive"
          echo "Downloading $file"
          curl -L --retry 5 -o "$file" "${{ steps.tcmeta.outputs.url }}"
          echo "::endgroup::"
          echo "::group::Extract toolchain"
          case "$file" in
            *.tar.xz) tar -C "$LLVM_TC_DIR" --strip-components=1 -xf "$file" ;;
            *.tar.zst) tar --zstd -C "$LLVM_TC_DIR" --strip-components=1 -xf "$file" ;;
            *) echo "Unknown archive: $file"; exit 1 ;;
          esac
          echo "::endgroup::"

      - name: Add toolchain to PATH
        run: echo "PATH=${{ env.LLVM_TC_DIR }}/bin:$PATH" >> $GITHUB_ENV

      # 3) ccache 캐시
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ inputs.wine_ref }}-${{ steps.tcmeta.outputs.tag }}-v1
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential clang lld git curl jq xz-utils rsync pkg-config \
            bison flex gettext autoconf automake libtool \
            libfreetype6-dev libfontconfig1-dev libglib2.0-dev libunwind-dev \
            libx11-dev libxext-dev libxi-dev libxrandr-dev libxrender-dev \
            libxcursor-dev libxfixes-dev libxinerama-dev libxcomposite-dev \
            libxdamage-dev libxkbcommon-dev libwayland-dev libdbus-1-dev \
            libasound2-dev libpulse-dev libudev-dev libvulkan-dev \
            ocl-icd-opencl-dev zlib1g-dev libjpeg-dev libpng-dev libtiff-dev \
            libgsm1-dev libldap2-dev libpcap0.8-dev ccache

      # 4) ccache 래퍼 설치: cross-클랭 호출을 ccache가 가로채게 함
      - name: Setup ccache masquerade for MinGW-LLVM triples
        run: |
          sudo mkdir -p /usr/local/bin
          for t in arm64ec-w64-mingw32 aarch64-w64-mingw32 i686-w64-mingw32; do
            for c in clang clang++; do
              sudo ln -sf "$(command -v ccache)" "/usr/local/bin/${t}-${c}"
            done
          done
          echo "CCACHE_DIR=${CCACHE_DIR}" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=${CCACHE_COMPRESS}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=${CCACHE_MAXSIZE}" >> $GITHUB_ENV
          ccache -p || true

      - name: Clone Valve wine (Proton branch)
        run: |
          git clone --depth=1 --branch "${{ inputs.wine_ref }}" https://github.com/ValveSoftware/wine.git src-wine
          git -C src-wine log -1 --oneline

      - name: Configure (ARM64EC + AArch64 + i386) with clang toolchain
        working-directory: src-wine
        run: |
          mkdir -p build && cd build
          ../configure \
            --enable-archs=arm64ec,aarch64,i386 \
            --with-mingw=clang \
            --disable-tests \
            --prefix="${PREFIX}"
          # 빌드 전 컴파일러 해상도 확인
          which arm64ec-w64-mingw32-clang
          which aarch64-w64-mingw32-clang
          which i686-w64-mingw32-clang

      - name: Build & Install (ccache on)
        working-directory: src-wine/build
        run: |
          ccache -z || true
          make -j"$(nproc)"
          ccache -s || true
          make install
          mkdir -p "${STAGE}"
          rsync -a "${PREFIX}/" "${STAGE}/"
          # 데스크톱/문서 제거(런타임만 남기기)
          rm -rf "${STAGE}/share/man" "${STAGE}/share/applications" \
                 "${STAGE}/share/icons" "${STAGE}/share/pixmaps" \
                 "${STAGE}/share/mime" || true

      # 5) 산출물 강제 검증: 필수 디렉토리 3종
      - name: Verify lib/wine contains required triplets
        run: |
          set -e
          for d in aarch64-unix aarch64-windows i386-windows; do
            test -d "${STAGE}/lib/wine/$d" || { echo "::error::$d missing under lib/wine"; exit 1; }
          done
          test -f "${STAGE}/share/wine/wine.inf" || { echo "::error::share/wine/wine.inf missing"; exit 1; }
          echo "[/bin]" && find "${STAGE}/bin" -maxdepth 1 -type f -printf "%f\n" | sort
          echo "[/lib/wine]" && find "${STAGE}/lib/wine" -maxdepth 1 -type d -printf "%f\n" | sort

      - name: Pack runtime (tar.xz, multi-thread)
        run: |
          tar -C "${STAGE}" -I 'xz -T0 -9' -cf wine-protonbase-arm64ec-wow64.tar.xz .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-protonbase-arm64ec-wow64
          path: wine-protonbase-arm64ec-wow64.tar.xz
          if-no-files-found: error
